version: '3'

services:
  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=audio_manager_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DATABASE_NAME=audio_manager_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A audio_manager worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
volumes:
  pgdata: