# Generated by Django 4.2.1 on 2023-05-25 01:22

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiomessage",
            name="audio_file",
            field=models.FileField(
                upload_to=audio.models.get_audio_messages_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="audiomessage",
            name="audio_url",
            field=models.URLField(default="https://example.com"),
        ),
    ]
