# Generated by Django 4.2.1 on 2023-05-27 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audio", "0004_remove_audiomessage_assigned_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiomessage",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
