# Generated by Django 4.2.1 on 2023-05-27 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0005_audiomessage_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiomessage",
            name="audio_url",
        ),
    ]
