# Generated by Django 4.2.1 on 2023-05-27 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audio", "0007_alter_audiomessage_assigned_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiomessage",
            name="assigned_users",
            field=models.ManyToManyField(
                related_name="audio_messages_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
