# Generated by Django 4.2.1 on 2023-06-03 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0008_alter_audiomessage_assigned_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiomessage",
            old_name="audio_file",
            new_name="audio_path",
        ),
    ]
