# Generated by Django 4.2.1 on 2023-06-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0009_rename_audio_file_audiomessage_audio_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiomessage",
            name="file_name",
            field=models.FileField(default="file", max_length=255, upload_to=""),
        ),
    ]
