# Generated by Django 4.2.1 on 2023-06-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0010_audiomessage_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiomessage",
            name="file_name",
            field=models.CharField(default="file", max_length=255),
        ),
    ]
