# Generated by Django 4.2.1 on 2023-06-03 17:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audio", "0011_alter_audiomessage_file_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiomessage",
            old_name="audio_path",
            new_name="audio_file",
        ),
    ]
