# Generated by Django 4.2.1 on 2023-06-03 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audio", "0012_rename_audio_path_audiomessage_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiomessage",
            name="assigned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="audio_messages_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="audiomessage",
            name="duration",
            field=models.DurationField(blank=True),
        ),
    ]
