# Generated by Django 4.2.1 on 2023-06-11 23:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("audio", "0014_alter_audiomessage_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiomessage",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
