# Generated by Django 4.2.1 on 2023-06-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_user_groups_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
