# Generated by Django 4.2.1 on 2023-06-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=True),
        ),
    ]
